#' Hazard Ratio dot plot with 95CI generated by coxph function of survival R package.
#' 
#' @param df dataframe object: must have columns "exp.coef.", "Pr...z..", "lower.95", "upper.95" and "x".
#' @param log10 boolean: -log10 transform hazard ratio & its CI
#' @param exclude string vector: List of x elements to exclude
#' @param filename string: ggplot2 filename parameter
#' @param width integer: ggplot2 width parameter
#' @param height integer: ggplot2 height parameter
#' @return Plot object. If filename provided, plot will also be saved
#' @examples
#' Hazard_Ratio_Plot(df = HR.df, log10 = FALSE, exclude = c("Strain1", "Strain2"), filename = "./Plots/test.pdf", width = 12) 
Hazard_Ratio_Plot <- function(df, log10 = TRUE, exclude = c(), filename = NA, width = NA, height = NA){
  HR.df <- df[!df$x %in% exclude, ]
  HR.df$sign <- HR.df$Pr...z.. < 0.05
  HR.df$down <- HR.df$exp.coef. < 1
  HR.df$color <- "not_sign"
  HR.df$color[HR.df$sign & HR.df$down] <- "beneficial"
  HR.df$color[HR.df$sign & !HR.df$down] <- "detrimental"
  
  if(log10){
    HR.df$lower <- log10(1 / HR.df$lower.95)
    HR.df$upper <- log10(1 / HR.df$upper.95)
    HR.df$HR <- log10(1 / HR.df$exp.coef.)
  } else {
    HR.df$lower <- 1 / HR.df$lower.95
    HR.df$upper <- 1 / HR.df$upper.95
    HR.df$HR <- 1 / HR.df$exp.coef.
  }
  
  HR.df$x <- factor(HR.df$x, levels = HR.df[order(-HR.df$HR), "x"])
  
  HR.plot <-
    ggplot(HR.df, aes(x = x, y = HR, color = color)) +
    geom_point() +
    geom_errorbar(aes(ymin = lower, ymax = upper)) +
    scale_color_manual(values = c("not_sign" = "grey",
                                  "beneficial" = "green",
                                  "detrimental" = "red")) +
    ylab("-log10(HR)") +
    xlab("Strain") +
    theme_bw() + 
    theme(panel.border = element_blank(), 
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(), 
          axis.line = element_line(colour = "black"),
          axis.text.x = element_text(angle = 90))
  
  if(!is.na(filename)){
    ggsave(HR.plot, filename = filename, width = width, height = height)
  }
  
  return(HR.plot)
}