#' Label passed gene list on the Running GSEA plot generated by cluster porfiler package.
#' 
#' @param gsea GSEA object.
#' @param gs integer: Index of Gene Set to plot from passed GSEA object.
#' @param title string: Title of generated plot
#' @param gene_list string list: list of gene names to label
#' @return Labeled plot object
#' @examples
#' gseaplot2_labeled(all_GSEA$Contrast_1, 1, "Response To Stress", c("gene-2", "gene-3"))
library("ggplot2")
library("clusterProfiler")

gseaplot2_labeled <- function(gsea, gs, title, gene_list) {
	search_name <- unlist(lapply(gene_list, FUN = toupper))
	loc_x <- match(search_name, names(gsea@geneList))
	label_df <- data.frame(genes, search_name, loc_x, loc_y = rep(0, length(loc_x)))
	
	g <- gseaplot2(gsea, gs, subplots = 1)
	g2 <- gseaplot2(gsea, gs, subplots = 2)
	g3 <- gseaplot2(gsea, gs, subplots = 3)
  
	g$theme <- g$theme + theme(axis.text.x=element_blank(),
								axis.line.x=element_blank(),
								axis.ticks.x=element_blank(),
								plot.margin = unit(c(0, 0.5, 0, 0.5), "cm"),
								plot.title = element_text(hjust = 0.5))
	
	g <- g + 
		geom_point(data = label_df, colour = "red", aes(x=loc_x, y=loc_y)) +
		ggtitle(title) +
		geom_label_repel(data = label_df, colour = "black", 
						aes(x=loc_x, y=loc_y, label=genes), 
						size = 3.5, box.padding = 3, label.size=NA)
	
	g2$theme <- g2$theme + theme(axis.text.x=element_blank(),
								axis.line.x=element_blank(),
								axis.ticks.x=element_blank(),
								plot.margin = unit(c(0, 0.5, 0, 0.5), "cm"))
	
	g3$theme <- g3$theme + theme(plot.margin = unit(c(0, 0.5, 0, 0.5), "cm"))
	
	return(plot_grid(plotlist = list(g, g2, g3), 
					ncol = 1, align = "v", 
					rel_heights = c(1.5, 0.5, 1)))
}
